# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 01:36
from __future__ import unicode_literals

import foundation.models.base
import foundation.models.fields
import foundation.models.manager
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from . import generate_initial_data


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', foundation.models.fields.SlugField(editable=False, max_length=25, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=(foundation.models.base.ControllerView, models.Model),
            managers=[
                ('objects', foundation.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', foundation.models.fields.SlugField(editable=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('publish', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs.Blog')),
            ],
            options={
                'ordering': ['-created'],
                'verbose_name': 'Blog Entry',
                'verbose_name_plural': 'Blog Entries',
            },
            bases=(foundation.models.base.ControllerView, models.Model),
            managers=[
                ('objects', foundation.models.manager.Manager()),
            ],
        ),
        migrations.RunPython(generate_initial_data),
    ]
